apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jzggdj0ra-nodejs 
  janus-idp.io/tekton: jzggdj0ra-nodejs
  backstage.io/kubernetes-id: jzggdj0ra-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jzggdj0ra-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  