apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jzggdj0ra-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jzggdj0ra-nodejs 
  name: jzggdj0ra-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jzggdj0ra-nodejs 
